export const PAGE_ROUTE = {
  dashboard: "/",
  data: "particulate-matter",
  userManament: "user-manament",
  smartg: "smart-g",
  particulateMatter: "particulate-matter",
  carbonDioxide: "carbon-dioxide",
  oxygen: "oxygen",
  humidity: "humidity",
  pressure: "pressure",
  temperature: "temperature",
  uv: "uv",
  sound: "sound",
  carbonMonoxide: "carbon-monoxide",
  ammonia: "ammonia",
  nitrogenDioxide: "nitrogen-dioxide",
  sulfurDioxide: "sulfur-dioxide",
  windDirection: "wind-direction",
  windSpeed: "wind-speed",
  rainfall: "rainfall",
};
export const API_ROUTE = {
  dashboard: "/api/dashboard-query",
  data: "/api/find-data",
  table: "/api/query-data-table",
  pm: "/api/find-pm",
};
