"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/index.css";
import TopNav from "@/components/top-nav";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Red Station",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#EDFBFF]`}
      >
        <QueryClientProvider client={queryClient}>
          <>
            <TopNav />
            {children}
          </>
        </QueryClientProvider>
      </body>
    </html>
  );
}
